version: 2
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: /app/build.gradle.kts  # Location of the build.gradle or build.gradle.kts file
    schedule:
      interval: "weekly"
    #open-pull-requests-limit: 10
    reviewers:
      - "Le-Mael"
    assignees:
      - "Le-Mael"
    ignore:
      - dependency-name: "com.example.old-dependency"
        versions: ["1.x"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /.github/workflows  # Root directory where .github/workflows are stored
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Le-Mael"
    assignees:
      - "Le-Mael"
