version: 2
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"  # Location of the build.gradle or build.gradle.kts file
    schedule:
      interval: "daily"
    #open-pull-requests-limit: 10
    reviewers:
      - "Le-Mael"
    assignees:
      - "Le-Mael"


  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"  # Root directory where .github/workflows are stored
    schedule:
      interval: "daily"
    #open-pull-requests-limit: 5
    reviewers:
      - "Le-Mael"
    assignees:
      - "Le-Mael"
