name: PMD Analysis

on: [push, pull_request]

jobs:
  pmd_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Run PMD
      uses: sfdx-actions/pmd@v0.3.0
      with:
        src: './src'
        ruleset: './rulesets/java/quickstart.xml'
        format: 'xml'
        output: 'pmd_output.xml'
        options: '--failOnViolation true --maxViolations 10'

    - name: Check PMD violations
      run: |
        violations=$(grep -c '<violation' pmd_output.xml)
        if [ "$violations" -gt 10 ]; then
          echo "Too many PMD violations: $violations"
          exit 1
        else
          echo "PMD violations are within the acceptable limit: $violations"
        fi
