name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          publish_results: true

      - name: Upload Scorecard report
        uses: actions/upload-artifact@v3
        with:
          name: scorecard-report
          path: results.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif